[package]
name = "flappy-bird-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt = "1.0.0"
cortex-m = "0.7.7"
embedded-hal = "1.0.0"
embedded_hal_mpu6050_driver = { path = "crates/embedded_hal_mpu6050_driver/", default-features = false }

[build-dependencies]
cc = "1.2.40"
